FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt .
COPY app.py .

RUN apt update && apt install -y iputils-ping

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001
CMD ["python", "app.py"]
